import type { SupportedLanguage } from "@/lib/language";

export const classesDetailedDescriptions: Record<SupportedLanguage, string[]> =
  {
    es: [
      "Una introducción amplia a la cultura del jazz: su origen en comunidades afroamericanas, su dimensión social y por qué se convirtió en una forma artística única. Entenderás sus bases estéticas para escuchar el resto del curso con criterio musical e histórico.",
      "Profundizamos en la heterogeneidad sonora del jazz y en la idea de “sonido propio”. Verás cómo timbre, articulación y fraseo construyen identidad artística, y por qué en jazz no existe una sola forma “correcta” de sonar.",
      "Analizamos los antecedentes históricos tras la Guerra Civil en EE.UU. y la relación entre spirituals, gospel y blues. Comprenderás cómo estas tradiciones dieron forma al lenguaje emocional y expresivo del jazz temprano.",
      "Estudiamos la improvisación como núcleo creativo del jazz, distinguiendo recursos melódicos, rítmicos y armónicos. Aprenderás a reconocer paráfrasis, desarrollo motívico y enfoques modales en ejemplos reales.",
      "Exploramos el ragtime como antecedente decisivo del jazz y su aporte rítmico. Conectarás su escritura pianística y su síncopa con los primeros estilos de Nueva Orleans y la transición hacia el jazz moderno.",
      "Nos enfocamos en el ritmo: swing feel, acentuación, interacción de la sección rítmica y evolución histórica. Entenderás cómo batería, contrabajo y piano transforman la energía musical de cada época.",
      "Descubrirás qué son las jam sessions y por qué fueron esenciales para la evolución del jazz. Verás cómo el “blowing” consolidó repertorios, lenguaje común y una cultura de aprendizaje entre músicos.",
      "Trabajamos composición y arreglo en jazz desde una mirada práctica: escritura para instrumentistas concretos, color tímbrico y balance entre estructura e improvisación. Aprenderás cómo el arreglo potencia la identidad de un ensamble.",
      "Recorremos el paso de las marching bands a los primeros grupos de jazz, con foco en instrumentación y función musical. Entenderás cómo se formó la sonoridad colectiva que definió la etapa inicial del género.",
      "Estudiamos la era del swing y el impacto de las big bands en la expansión internacional del jazz. Analizarás repertorio, función de secciones y el diálogo entre arreglos escritos y espacio improvisado.",
      "Abordamos la transición hacia combos modernos, bop y hard bop, junto con el nuevo rol de la sección rítmica. Comprenderás la evolución de la interacción musical y la sofisticación armónica en formatos pequeños.",
      "Volvemos a la improvisación con enfoque avanzado: construcción de discurso, tensión y resolución, y desarrollo narrativo del solo. Aprenderás a escuchar cómo grandes solistas organizan ideas en tiempo real.",
      "Analizamos la relación entre jazz y entretenimiento, desde circuitos populares hasta su legitimación artística. Verás cómo cambió la percepción del género y su lugar en la industria cultural.",
      "Estudiamos el canto jazzístico en su primera etapa: fraseo, swing vocal y uso expresivo del texto. Conocerás figuras clave y recursos que marcaron la identidad de las grandes vocalistas.",
      "Cerramos con la evolución del canto jazz en la era swing y su legado posterior. Entenderás cómo técnica, interpretación y personalidad artística definieron modelos vocales que siguen vigentes hoy.",
    ],
    en: [
      "A broad introduction to jazz culture: its roots in African American communities, its social dimension, and why it became a unique artistic language. You build a historical and aesthetic foundation for the rest of the course.",
      "We dive into jazz’s sonic diversity and the concept of personal sound. You see how timbre, articulation, and phrasing shape artistic identity, and why jazz values individuality over standardization.",
      "We examine the post–Civil War historical background in the U.S. and the links between spirituals, gospel, and blues. You understand how these traditions shaped early jazz expression and emotional depth.",
      "Improvisation is explored as the central creative engine of jazz, across melodic, rhythmic, and harmonic approaches. You learn to identify paraphrase, motivic development, and modal thinking in practice.",
      "This lesson focuses on ragtime as a decisive precursor to jazz and its rhythmic legacy. You connect piano writing and syncopation to early New Orleans styles and the birth of modern jazz language.",
      "We focus on rhythm: swing feel, accents, section interaction, and historical evolution. You understand how drums, bass, and piano redefine musical energy across different jazz eras.",
      "You discover how jam sessions shaped jazz culture and musicianship. We analyze how blowing sessions helped consolidate repertoire, shared language, and collaborative learning among players.",
      "We cover jazz composition and arranging in practical terms: writing for specific musicians, timbral color, and structure vs. improvisation. You see how arrangements amplify ensemble identity.",
      "From marching bands to early jazz groups, we trace instrumentation and functional roles. You learn how collective texture and role distribution formed the sound of early jazz ensembles.",
      "We study the swing era and the international rise of big bands. You analyze section writing, repertoire logic, and the balance between arranged material and improvisational space.",
      "This class addresses the shift to modern combos, bop, and hard bop, including new rhythm-section roles. You understand the move toward tighter interaction and harmonic sophistication in small groups.",
      "An advanced improvisation focus: solo architecture, tension-release, and narrative pacing. You learn to hear how major soloists build coherent musical storytelling in real time.",
      "We examine jazz and entertainment, from popular circuits to artistic legitimization. You understand how the genre’s public image evolved and how that changed its cultural status.",
      "Jazz singing, part 1: vocal swing, phrasing, and expressive use of lyrics. You study key artists and stylistic tools that shaped the classic jazz vocal tradition.",
      "We close with jazz singing in the swing era and its long-term legacy. You connect technique, interpretation, and artistic personality to the vocal models still influential today.",
    ],
    fr: [
      "Une introduction large à la culture jazz : ses racines afro-américaines, sa portée sociale et les raisons de son originalité artistique. Vous construisez une base historique et esthétique pour tout le parcours.",
      "Nous explorons l’hétérogénéité sonore du jazz et la notion de “son personnel”. Vous voyez comment timbre, articulation et phrasé créent l’identité d’un musicien.",
      "Analyse des antécédents historiques après la guerre de Sécession et des liens entre spirituals, gospel et blues. Vous comprenez comment ces traditions ont modelé le langage expressif du jazz.",
      "L’improvisation est étudiée comme moteur créatif central, avec ses ressources mélodiques, rythmiques et harmoniques. Vous apprenez à reconnaître paraphrase, développement motivique et approche modale.",
      "Le ragtime est présenté comme un antécédent décisif du jazz. Vous reliez sa syncope et son écriture pianistique aux premiers styles de La Nouvelle-Orléans.",
      "Leçon centrée sur le rythme : swing feel, accentuation, dialogue de la section rythmique et évolution historique. Vous comprenez le rôle transformateur batterie-contrebasse-piano.",
      "Vous découvrez les jam sessions et leur rôle dans la construction de la culture jazz. Nous voyons comment elles ont renforcé le répertoire, le langage commun et l’apprentissage collectif.",
      "Composition et arrangement en jazz : écrire pour des musiciens précis, travailler la couleur sonore et équilibrer structure et improvisation. Vous voyez comment un arrangement affirme l’identité d’un groupe.",
      "Des marching bands aux premiers ensembles de jazz, nous suivons l’évolution des formations et des fonctions instrumentales. Vous identifiez la naissance de la texture collective du jazz initial.",
      "Étude de l’ère swing et de l’expansion internationale des big bands. Vous analysez l’écriture en sections, le répertoire et l’équilibre entre matière écrite et improvisation.",
      "Transition vers les combos modernes, le bop et le hard bop, avec un nouveau rôle de la section rythmique. Vous comprenez l’évolution de l’interaction et de la complexité harmonique.",
      "Approche avancée de l’improvisation : construction du solo, tension-détente et narration musicale. Vous apprenez à écouter l’organisation du discours en temps réel.",
      "Nous analysons le lien entre jazz et divertissement, des circuits populaires à la reconnaissance artistique. Vous comprenez l’évolution de son image publique et de son statut culturel.",
      "Chant jazz 1 : swing vocal, phrasé et expressivité du texte. Vous découvrez les artistes clés et les procédés qui ont marqué la tradition vocale classique.",
      "Conclusion sur le chant jazz à l’époque swing et son héritage durable. Vous reliez technique, interprétation et personnalité artistique dans les modèles vocaux actuels.",
    ],
    pt: [
      "Uma introdução ampla à cultura do jazz: suas raízes afro-americanas, contexto social e os elementos que transformaram o gênero em uma linguagem artística única. Você cria base histórica e estética para entender o curso inteiro.",
      "Aprofundamos a heterogeneidade sonora do jazz e a ideia de “som pessoal”. Você entende como timbre, articulação e fraseado constroem identidade musical e por que a individualidade é central no jazz.",
      "Analisamos o contexto histórico pós-Guerra Civil nos EUA e a ligação entre spirituals, gospel e blues. Você compreende como essas matrizes moldaram o caráter expressivo do jazz inicial.",
      "Estudamos a improvisação como núcleo criativo do jazz, passando por recursos melódicos, rítmicos e harmônicos. Você aprende a reconhecer paráfrase, desenvolvimento motívico e abordagens modais na prática.",
      "Exploramos o ragtime como antecedente decisivo do jazz e seu legado rítmico. Você conecta escrita pianística, síncope e a transição para os primeiros estilos de Nova Orleans.",
      "Foco total em ritmo: swing feel, acentuação, interação da seção rítmica e evolução histórica. Você entende como bateria, contrabaixo e piano redefinem a energia musical em cada período.",
      "Você vai entender o que são jam sessions e por que elas foram fundamentais na cultura do jazz. A aula mostra como o “blowing” consolidou repertório, linguagem comum e aprendizado coletivo entre músicos.",
      "Composição e arranjo em jazz na prática: escrita para músicos específicos, cor tímbrica e equilíbrio entre estrutura e improviso. Você percebe como o arranjo fortalece a identidade de um grupo.",
      "Percorremos a passagem das marching bands para os primeiros grupos de jazz, com foco em instrumentação e função musical. Você entende como nasce a sonoridade coletiva da fase inicial do gênero.",
      "Estudamos a era do swing e o papel das big bands na internacionalização do jazz. Você analisa escrita por seções, lógica de repertório e o diálogo entre partes escritas e improvisadas.",
      "A aula cobre a transição para combos modernos, bop e hard bop, com novo papel da seção rítmica. Você compreende a evolução da interação musical e o aumento da sofisticação harmônica.",
      "Improvisação em nível avançado: construção de discurso, tensão e resolução, e narrativa de solo. Você aprende a ouvir como grandes solistas organizam ideias musicais em tempo real.",
      "Analisamos a relação entre jazz e entretenimento, dos circuitos populares à legitimação artística. Você entende como a percepção pública do gênero mudou ao longo do tempo.",
      "Canto jazz 1: fraseado, swing vocal e uso expressivo da letra. Você conhece artistas fundamentais e os recursos técnicos que moldaram a tradição vocal clássica do jazz.",
      "Encerramos com o canto jazz na era do swing e seu legado posterior. Você conecta técnica, interpretação e personalidade artística aos modelos vocais que influenciam até hoje.",
    ],
  };
