export type QuizSeedQuestion = {
  prompt: string;
  explanation?: string;
  sourceLabel?: string;
  options: Array<{
    text: string;
    isCorrect: boolean;
  }>;
};

const OPTION_LABELS = ['A', 'B', 'C', 'D', 'E'];

function q(
  prompt: string,
  correct: string,
  distractors: [string, string, string, string],
  explanation?: string,
  sourceLabel?: string
): QuizSeedQuestion {
  return {
    prompt,
    explanation,
    sourceLabel,
    options: [
      { text: correct, isCorrect: true },
      ...distractors.map((text) => ({ text, isCorrect: false })),
    ],
  };
}

export const LESSON_QUIZ_BANKS: Record<number, QuizSeedQuestion[]> = {
  1: [
    q('Em que cidade o jazz aparece de forma espontanea segundo os apontes?', 'New Orleans', ['Chicago', 'Kansas City', 'Memphis', 'Boston'], 'Os apontes localizam o surgimento espontaneo do jazz em New Orleans.', 'Clase 1'),
    q('Que mistura cultural aparece na base do jazz desde o inicio?', 'Elementos afrologicos e eurologicos', ['Elementos apenas africanos', 'Elementos apenas europeus', 'Elementos exclusivamente latinos', 'Elementos exclusivamente asiaticos'], undefined, 'Clase 1'),
    q('Segundo uma das teorias citadas, o que significaria jaja em bantu?', 'Dancar ou soar', ['Marchar ou rezar', 'Escrever ou contar', 'Chorar ou sofrer', 'Calar ou esconder'], undefined, 'Clase 1'),
    q('Qual destes NAO aparece como elemento essencial da cultura do jazz na aula 1?', 'Uniformidade timbrica absoluta', ['Sound proprio', 'Improvisacao', 'Liberdade ritmica e swing', 'Sonoridades inauditas'], undefined, 'Clase 1'),
    q('O que o jazz herda da fala e da musica negra, segundo a aula?', 'A importancia da sonoridade pessoal', ['A obrigacao de tocar sem matizes', 'A busca por homogeneidade coral', 'A eliminacao do timbre pessoal', 'A negacao da voz como instrumento'], undefined, 'Clase 1'),
    q('O que descreve o significant tone na estetica afro-americana?', 'A relacao entre significado e qualidade do som', ['A afinacao temperada europeia', 'A duracao exata de cada compasso', 'A ausencia de vibrato', 'A escrita harmonica em partitura'], undefined, 'Clase 1'),
    q('Que comparacao os apontes fazem entre Coleman Hawkins e Lester Young em Body and Soul?', 'Eles possuem sounds pessoais claramente distinguiveis', ['Tocam com o mesmo colorido exato', 'Ambos rejeitam o fraseado pessoal', 'Os dois soam como Stan Getz', 'Ambos usam apenas sordina'], undefined, 'Clase 1'),
    q('Quando comeca a se consolidar uma cultura jazzistica mais autonoma, segundo Peter Townsend?', 'Entre o fim dos anos 20 e as decadas de 30 e 40', ['No seculo XVIII', 'Somente depois de 1970', 'Na decada de 1880', 'Apos o free jazz'], undefined, 'Clase 1'),
    q('O que separa progressivamente o jazz do entertainment?', 'A consolidacao de praticas, valores e espacos proprios', ['O desaparecimento da improvisacao', 'A proibicao do swing', 'A eliminacao dos solistas', 'A renuncia as jam sessions'], undefined, 'Clase 1'),
    q('O que o Minton’s representa nos anos 40 segundo os apontes?', 'A formulacao de uma cultura jazzistica pura ligada ao bop', ['O retorno do ragtime classico', 'O triunfo da opereta', 'A fundacao do swing europeu', 'O fim do pequeno formato'], undefined, 'Clase 1'),
    q('Qual o papel de Django Reinhardt na mundializacao do jazz segundo a aula?', 'Ampliar o jazz com a marca da cultura cigana', ['Introduzir a opera italiana no jazz', 'Eliminar a oralidade do genero', 'Transformar o jazz em musica apenas escrita', 'Substituir a improvisacao por marchas militares'], undefined, 'Clase 1'),
    q('Qual afirmacao resume melhor a postura final da aula sobre definir jazz?', 'Evita-se uma definicao totalmente fechada e parte-se de seus elementos musicais', ['Existe apenas uma definicao valida', 'Conclui-se que o jazz nao tem historia', 'Define-se jazz apenas pela instrumentacao', 'Reduce-se jazz a entretenimento'], undefined, 'Clase 1'),
    q('Que expressao os apontes usam para a identidade reconhecivel de um musico por seu som?', 'Silueta sonora', ['Cadencia escrita', 'Escala rigida', 'Metrica uniforme', 'Plantilla classica'], undefined, 'Clase 1'),
  ],
  2: [
    q('Que ideal sonoro dominou a musica culta ocidental desde o seculo XV?', 'A homogeneidade sonora', ['A heterogeneidade extrema', 'A sincopa permanente', 'O growl vocal', 'A ausencia de timbre'], undefined, 'Clase 2'),
    q('O que a heterogeneidade sonora valoriza no jazz?', 'A mistura de sonoridades diversas', ['A pureza uniforme do timbre', 'A eliminacao de ruidos expressivos', 'A afinacao sem vibrato', 'A negacao do colorido instrumental'], undefined, 'Clase 2'),
    q('Que saxofonista leva ao limite a mistura entre som e sopro nos apontes?', 'Ben Webster', ['Stan Getz', 'Coleman Hawkins', 'Charlie Parker', 'Paul Desmond'], undefined, 'Clase 2'),
    q('Qual contraste e citado entre Helen Merrill e Clifford Brown?', 'A voz de Merrill preserva ar e sopro diante da homogeneidade da trompete', ['Ambos produzem exatamente o mesmo timbre', 'Brown usa growl e Merrill nao canta', 'Merrill toca trombone e Brown piano', 'Nao ha contraste citado entre os dois'], undefined, 'Clase 2'),
    q('Para que servem a straight mute e o plunger na trompete de jazz?', 'Para modificar o timbre e produzir efeitos como growl', ['Para afinar uma oitava abaixo', 'Para eliminar todo colorido nasal', 'Para converter a trompete em corda', 'Para tocar sem ar'], undefined, 'Clase 2'),
    q('Quem e citado como mestre do growl na orquestra de Ellington?', 'Cootie Williams', ['Bill Evans', 'Paul Chambers', 'Oscar Peterson', 'Art Blakey'], undefined, 'Clase 2'),
    q('Que sonoridade Louis Armstrong ajudou a construir com a harmon mute?', 'Uma sonoridade depois decisiva para o clima noturno de Miles Davis', ['O som tipico do ragtime pianistico', 'O timbre puro de fanfarra militar', 'A ausencia total de vibrato', 'Um estilo exclusivamente vocal'], undefined, 'Clase 2'),
    q('Que instrumento Sidney Bechet toca ao produzir growl sem artificios?', 'Clarinete ou sax soprano', ['Trombone baixo', 'Piano vertical', 'Vibrafone', 'Contrabaixo'], undefined, 'Clase 2'),
    q('O que Slam Stewart faz alem de tocar contrabaixo?', 'Dobra a linha cantando uma oitava acima', ['Usa apenas percussao corporal', 'Para de tocar para recitar', 'Troca o contrabaixo por guitarra', 'Toca exclusivamente com slide'], undefined, 'Clase 2'),
    q('Como o jazz trata um som que a tradicao classica poderia chamar de ruido?', 'Como cor musical viva e expressiva', ['Como erro que deve sempre ser eliminado', 'Como defeito sem valor artistico', 'Como algo incompatível com swing', 'Como afinacao proibida'], undefined, 'Clase 2'),
    q('Que orquestra aparece no exemplo de Black and Tan Fantasy?', 'A orquestra de Duke Ellington', ['A de Count Basie', 'A de Stan Kenton', 'A de Benny Goodman', 'A de Woody Herman'], undefined, 'Clase 2'),
    q('Que diferenca estetica entre jazz e certa tradicao ocidental esta no centro desta aula?', 'A beleza pode nascer de timbres misturados e nao apenas do som puro', ['O jazz rejeita qualquer timbre instrumental', 'O jazz exige a mesma emissao em todos os musicos', 'O jazz elimina a expressividade vocal', 'O jazz usa apenas sonoridade homogenea'], undefined, 'Clase 2'),
    q('Que palavra os apontes usam para descrever o efeito do growl?', 'Grunhido', ['Arpejo limpo', 'Falsete neutro', 'Pedal harmonico', 'Contraponto exato'], undefined, 'Clase 2'),
  ],
  3: [
    q('O que as blue notes introduziam em relacao a escala europeia?', 'Uma flutuacao sobre o terceiro e o setimo graus', ['Uma fixacao absoluta do primeiro grau', 'Uma afinacao exclusivamente cromatica escrita', 'O desaparecimento do vibrato', 'A substituicao da melodia por recitativo'], undefined, 'Clase 3'),
    q('Como muitos colonos brancos interpretaram erroneamente as caracteristicas vocais africanas?', 'Como sinais de inferioridade e incapacidade de adaptacao', ['Como prova de formacao academica superior', 'Como imitacao exata do bel canto', 'Como resultado do canto gregoriano', 'Como tecnica exclusiva do piano'], undefined, 'Clase 3'),
    q('O que eram os spirituals ou gospel segundo a aula?', 'Um compromisso entre costumes africanos e cancioneros protestantes ingleses', ['Uma copia exata da opera italiana', 'Uma forma puramente militar de canto', 'Cancoes escritas so para big bands', 'Baladas francesas sem relacao religiosa'], undefined, 'Clase 3'),
    q('Que mudanca tematica ocorre apos a emancipacao nos cantos religiosos negros?', 'Aproximam-se mais do Novo Testamento e da figura de Jesus', ['Abandonam toda referencia biblica', 'Tornam-se exclusivamente instrumentais', 'Passam a falar apenas da Europa', 'Transformam-se em polcas'], undefined, 'Clase 3'),
    q('Que estrutura de dialogo religioso antecipa uma pratica central do jazz?', 'O pastor pronuncia e o povo responde', ['O coro canta sempre sem lider', 'O pregador toca bateria sozinho', 'A congregacao guarda silencio permanente', 'O orgao substitui toda voz'], undefined, 'Clase 3'),
    q('Como se chama no jazz o estribilho curto e eficaz que responde ao solista?', 'Riff', ['Bridge', 'Outro', 'Cadence', 'Mute'], undefined, 'Clase 3'),
    q('Que origem provavel do blues a classe sugere?', 'Depois da Guerra Civil, com negros libertos e itinerantes', ['Na corte barroca francesa', 'Antes de toda escravidao na America', 'No bebop dos anos 40', 'Dentro dos conservatorios alemaes'], undefined, 'Clase 3'),
    q('Que forma W.C. Handy ajuda a fixar para o blues?', '12 compassos em estrutura AAB', ['16 compassos em ABCA', '8 compassos em AA', '24 compassos em rondo', '32 compassos em AABA'], undefined, 'Clase 3'),
    q('Que sentimento aparece como central no protagonista do blues?', 'Angustia', ['Indiferenca total', 'Neutralidade ritmica', 'Alegria militar', 'Obediencia liturgica'], undefined, 'Clase 3'),
    q('Que papeis culturais sao atribuidos ao cantor de blues?', 'Griot africano e uma especie de psicoterapeuta', ['Diretor de fanfarra e violinista classico', 'Copista e notario', 'Apenas bailarino e ator mudo', 'Pregador sem relacao musical'], undefined, 'Clase 3'),
    q('O que Frederick Olmsted descreve em 1853 ao observar trabalhadores negros?', 'Um canto lancado por uma voz e retomado por outras como coro', ['Uma orquestra sinfonica completa', 'Uma marcha militar escrita', 'Uma fuga barroca', 'Uma opera em italiano'], undefined, 'Clase 3'),
    q('Que tema aparece com frequencia nos blues rurais segundo os apontes?', 'Relacoes sexuais vistas como instaveis e angustiantes', ['Astronomia europeia', 'Geometria classica', 'Politica parlamentar francesa', 'Repertorio exclusivo de igreja'], undefined, 'Clase 3'),
    q('O que tornou Blind Lemon Jefferson lendario na aula?', 'Seu blues angustiado e a tecnica com gargalo ou faca na guitarra', ['Sua carreira como diretor de big band em Nova York', 'Seu uso exclusivo de piano preparado', 'Sua carreira como cantor de opera', 'Sua rejeicao total ao blues'], undefined, 'Clase 3'),
  ],
  4: [
    q('Que forma totaliza 32 compassos na aula sobre baladas?', 'AABA de 8 mais 8 mais 8 mais 8', ['AAB de 4 mais 4 mais 4', 'AB de 16 mais 16', 'AAA de 12 mais 12 mais 12', 'Rondo de 10 mais 10 mais 10'], undefined, 'Clase 4'),
    q('Que funcao cumpre o bridge na forma AABA?', 'Introduz uma ideia nova antes do retorno final', ['Repete exatamente a primeira frase', 'Elimina a harmonia do tema', 'Fecha a obra apos quatro compassos', 'Substitui a melodia por percussao'], undefined, 'Clase 4'),
    q('Qual e a estrutura basica do blues segundo esta aula?', 'AAB em 12 compassos', ['ABBA em 16 compassos', 'AABA em 32 compassos', 'ABA em 9 compassos', 'AA em 24 compassos'], undefined, 'Clase 4'),
    q('O que se chama chorus na linguagem do jazz?', 'O ciclo completo da progressao harmonica do tema', ['Somente o estribilho cantado', 'A introducao livre do baterista', 'O silencio entre solos', 'A ultima nota do saxofone'], undefined, 'Clase 4'),
    q('De que depende em grande parte a dificuldade para improvisar sobre um tema?', 'Da complexidade de sua progressao harmonica', ['Da cor da roupa do solista', 'Da quantidade de publico', 'Do tamanho do palco', 'De haver cantor ou nao'], undefined, 'Clase 4'),
    q('Que musico e citado por ampliar e complexificar a harmonia do blues?', 'Charlie Parker', ['Louis Prima', 'Glenn Miller', 'Bing Crosby', 'Chet Baker'], undefined, 'Clase 4'),
    q('Que standard aparece como exemplo de alta dificuldade harmonica?', 'Cherokee', ['C Jam Blues', 'When the Saints Go Marching In', 'Tequila', 'La Bamba'], undefined, 'Clase 4'),
    q('O que significa dizer que um solo dura varios chorus?', 'Que o improvisador percorre varias vezes a estrutura do tema', ['Que muda de instrumento a cada volta', 'Que canta com coro gospel por cima', 'Que elimina a harmonia desde o inicio', 'Que toca apenas no bridge'], undefined, 'Clase 4'),
    q('Qual destes compositores e citado entre os mais aproveitados pelo jazz?', 'George Gershwin', ['Richard Wagner', 'Claudio Monteverdi', 'Jean-Baptiste Lully', 'Antonio Vivaldi'], undefined, 'Clase 4'),
    q('Que diferenca principal a aula destaca entre balada e blues em termos de forma?', 'A balada costuma apoiar-se em AABA e o blues em AAB', ['A balada nao tem acordes e o blues tem', 'O blues nunca e improvisado', 'A balada dura sempre 12 compassos', 'O blues usa sempre 32 compassos'], undefined, 'Clase 4'),
    q('Que tema de Monk aparece como exemplo na aula?', 'Blue Monk', ['So What', 'Giant Steps', 'Take Five', 'Spain'], undefined, 'Clase 4'),
    q('Que relacao existe entre forma do tema e improvisacao?', 'A forma sustenta o percurso do improvisador sobre os acordes', ['A forma desaparece completamente ao improvisar', 'Improvisacao so ocorre sem tema', 'O improvisador toca fora de toda progressao', 'Nao existe relacao entre ambos'], undefined, 'Clase 4'),
    q('O que acontece com a primeira ideia A na forma AABA?', 'Ela se apresenta e se repete antes do bridge', ['Aparece so uma vez e desaparece', 'Sempre a toca a bateria sozinha', 'E substituida por um riff fixo de baixo', 'E eliminada quando entra o cantor'], undefined, 'Clase 4'),
  ],
  5: [
    q('Que mao do piano mantem o um-pa regular no ragtime?', 'A mao esquerda', ['A mao direita', 'As duas em unissono', 'Nenhuma, isso cabe a bateria', 'Apenas o pe do pianista'], undefined, 'Clase 5'),
    q('O que a mao direita faz no piano ragtime?', 'Toca melodias sincopadas que deslocam os acentos', ['Marca sempre as tonicas sem sincopa', 'Imita marcha militar sem variacao', 'Faz apenas acordes longos sem ritmo', 'Nao participa da textura'], undefined, 'Clase 5'),
    q('Que compositores aparecem como grandes nomes do ragtime?', 'Scott Joplin e Tom Turpin', ['Duke Ellington e Count Basie', 'Charlie Parker e Dizzy Gillespie', 'Bill Evans e Herbie Hancock', 'Benny Goodman e Artie Shaw'], undefined, 'Clase 5'),
    q('Que aparelho ajudou a difundir o ragtime antes da era do disco?', 'A pianola com rolos', ['O magnetofone portatil', 'A radio FM estereo', 'O sintetizador digital', 'A televisao em cores'], undefined, 'Clase 5'),
    q('O que Jelly Roll Morton acrescentou em relacao ao ragtime mais rigido?', 'Uma sincopa mais suave e improvisada que antecipa o swing', ['A eliminacao total do ritmo binario', 'O desaparecimento do piano do ragtime', 'O retorno estrito ao coral europeu', 'A substituicao do jazz por valsas'], undefined, 'Clase 5'),
    q('Qual era o nome real de Jelly Roll Morton segundo os apontes?', 'Louis Ferdinand La Mente', ['Edward Kennedy Ellington', 'William Basie Jones', 'James P. Johnson', 'Charles Christopher Parker'], undefined, 'Clase 5'),
    q('Que relacao se estabelece entre ragtime e compositores europeus?', 'Varios compositores classicos adotaram elementos do ragtime', ['A Europa rejeitou completamente o ragtime', 'Ele so foi tocado em igrejas batistas', 'Nunca saiu do ambito de rua norte-americano', 'Foi proibido em salas de concerto'], undefined, 'Clase 5'),
    q('Que traco define a sincopa do ragtime?', 'Deslocar o acento harmonico e falsifica-lo', ['Reforcar sempre o acento forte exato', 'Suprimir toda regularidade binaria', 'Impor 5 por 4 em todos os casos', 'Eliminar a melodia do piano'], undefined, 'Clase 5'),
    q('Que formacoes de New Orleans adicionaram piano e se aproximaram do jazz?', 'As marching bands', ['Os quartetos de cordas vienenses', 'Os coros gregorianos', 'As orquestras de tango argentino', 'As fanfarras russas'], undefined, 'Clase 5'),
    q('Que estrutura tinha o ragtime primitivo de danca citado no inicio?', 'Frases de 4 e 8 compassos', ['Apenas frases de 3 compassos', 'Series de 11 compassos', 'Formas fixas de 32 compassos sem excecao', 'Uma nota sustentada por secao'], undefined, 'Clase 5'),
    q('Que obra muito conhecida de Scott Joplin aparece citada?', 'The Entertainer', ['My Favorite Things', 'Blue Train', 'Take the A Train', 'A Love Supreme'], undefined, 'Clase 5'),
    q('Que diferenca as marching bands negras apresentam em relacao as brancas segundo a aula?', 'A presenca de sincopa de raiz africana', ['A rejeicao completa de todo ritmo', 'O uso exclusivo de cordas friccionadas', 'O desaparecimento da percussao', 'A execucao de opera italiana'], undefined, 'Clase 5'),
    q('Que relacao entre ragtime e nascimento do jazz a aula destaca?', 'O ragtime foi antecedente decisivo que depois se flexibilizou rumo ao swing', ['O ragtime apareceu apos o bebop', 'O ragtime eliminou a improvisacao do jazz', 'O jazz nasceu sem qualquer relacao com ragtime', 'O ragtime substituiu New Orleans'], undefined, 'Clase 5'),
  ],
  6: [
    q('Que instrumento marcava o two beat no jazz inicial?', 'O bumbo', ['O ride', 'O vibrafone', 'A guitarra eletrica', 'O sax tenor'], undefined, 'Clase 6'),
    q('Em que tempos esse two beat inicial costumava se apoiar com forca?', 'No 1 e no 3', ['No 2 e no 4', 'Apenas no 4', 'Em todos igualmente desde o inicio', 'Fora do compasso'], undefined, 'Clase 6'),
    q('O que e sincopa segundo esta aula?', 'O deslocamento do acento forte para uma parte fraca do compasso', ['A repeticao exata do pulso forte', 'A eliminacao de toda metrica', 'O uso exclusivo de compassos ternarios', 'Um silencio ao fim da frase'], undefined, 'Clase 6'),
    q('O que Armstrong pediu a Baby Dodds para mudar o enfoque ritmico?', 'Dar importancia equivalente aos quatro tempos', ['Eliminar por completo a bateria', 'Tocar so com escovinhas no 2 e 4', 'Voltar ao ragtime puro', 'Passar toda a marcacao ao piano'], undefined, 'Clase 6'),
    q('O que Gene Krupa fez na transicao para o swing?', 'Foi deslocando a marcacao do bumbo para pratos e caixa', ['Retirou os pratos do set', 'Eliminou a sincopa', 'Suprimiu os breaks', 'Abandonou toda marcacao de pulso'], undefined, 'Clase 6'),
    q('Que inovacao se atribui a Papa Jo Jones?', 'Transferir a marcacao para o hi-hat e depois para o ride', ['Voltar a marcar tudo apenas no bumbo', 'Retirar a caixa do set', 'Converter a bateria em instrumento melodico unico', 'Eliminar o hi-hat'], undefined, 'Clase 6'),
    q('Que efeito o uso continuo de pratos cria no bop?', 'Um som continuo que iguala os quatro tempos', ['O desaparecimento do beat', 'Um padrao exclusivamente ternario', 'Um acompanhamento sem acentos', 'Silencio entre frases'], undefined, 'Clase 6'),
    q('Como os bateristas de bebop usam o bumbo?', 'Para drop bombs e comentarios ao solista', ['Como unica fonte regular de pulso', 'Apenas para marchas', 'Para substituir totalmente a caixa', 'Para tocar sem relacao com o grupo'], undefined, 'Clase 6'),
    q('Como se chamam esses acentos pontuais de bumbo no bop?', 'Dropping bombs', ['Walking bass', 'Head riffs', 'Blue notes', 'Shouts'], undefined, 'Clase 6'),
    q('Que aspecto do ritmo de jazz se reforca quando os quatro tempos recebem atencao mais equivalente?', 'A sensacao fluida do swing', ['A rigidez da marcha militar', 'O desaparecimento da improvisacao', 'A impossibilidade de comping', 'A anulacao do ride'], undefined, 'Clase 6'),
    q('Que tecnica de preenchimento entre frases e solos e citada para bateristas antigos?', 'Break', ['Unissono coral', 'Cluster', 'Cadenza operistica', 'Pedal point'], undefined, 'Clase 6'),
    q('Que baterista e descrito como ex-dancarino de tap e revolucionario do uso dos pratos?', 'Jo Jones', ['Max Roach', 'Elvin Jones', 'Tony Williams', 'Paul Motian'], undefined, 'Clase 6'),
    q('Que relacao o bop mantem com a bateria anterior apesar da mudanca?', 'Mantem o pulso, mas redistribui acentos e funcoes', ['Abandona toda referencia ao beat', 'Retorna ao ragtime original', 'Elimina caixa e pratos', 'Reduz a bateria a adorno visual'], undefined, 'Clase 6'),
  ],
  7: [
    q('Que versao sobre a origem do termo jamming aparece nos apontes?', 'Uma anedota ligada a Bix Beiderbecke e Louis Armstrong em Chicago', ['Uma teoria barroca vienense', 'Uma invencao de Duke Ellington em Paris', 'Uma palavra criada por Stan Kenton', 'Um termo militar da Guerra Civil espanhola'], undefined, 'Clase 7'),
    q('Como muitos clubes de Kansas City funcionavam para facilitar jams?', 'Com base fixa de secao ritmica e solistas entrando aos poucos', ['Com orquestra sinfonica integralmente escrita', 'Com coro religioso permanente', 'Sem improvisacao permitida', 'Apenas com piano solo'], undefined, 'Clase 7'),
    q('Que saxofonista sai vencedor da lendaria jam de 1934 segundo a aula?', 'Lester Young', ['Ben Webster', 'Coleman Hawkins', 'Hershel Evans', 'Johnny Hodges'], undefined, 'Clase 7'),
    q('Como Gunther Schuller define a jam session?', 'Como reuniao informal de musicos que tocam por prazer proprio', ['Como concerto religioso com partitura fixa', 'Como aula obrigatoria de conservatorio', 'Como ensaio militar', 'Como gravacao sem improvisacao'], undefined, 'Clase 7'),
    q('Que cantora protagoniza a famosa jam televisionada de 1956?', 'Billie Holiday', ['Ella Fitzgerald', 'Sarah Vaughan', 'Peggy Lee', 'Anita O Day'], undefined, 'Clase 7'),
    q('Que tema aparece nessa jam historica de 1956?', 'Fine and Mellow', ['Take Five', 'Spain', 'Blue in Green', 'Naima'], undefined, 'Clase 7'),
    q('Que traco do solo de Lester Young em 1956 e destacado?', 'Contencao expressiva marcada pelo desgaste fisico', ['Volume marcial e agressivo', 'Ausencia total de emocao', 'Estilo operistico', 'Rejeicao a qualquer interacao com Billie Holiday'], undefined, 'Clase 7'),
    q('O que Billie Holiday demonstra ao interagir com os solistas nessa jam?', 'Compreensao emocional e musical muito fina dos aportes alheios', ['Indiferenca aos acompanhantes', 'Rejeicao a toda improvisacao alheia', 'Preferencia por cantar sem grupo', 'Dependencia exclusiva de partitura'], undefined, 'Clase 7'),
    q('Que cidade aparece como grande laboratorio de jam sessions nesta aula?', 'Kansas City', ['Madrid', 'Roma', 'Berlim', 'Lisboa'], undefined, 'Clase 7'),
    q('Que ideia resume melhor o valor cultural da jam?', 'E um espaco de prazer, intercambio e afirmacao da linguagem do jazz', ['E um tramite administrativo previo ao concerto', 'Substitui por completo o repertorio', 'E pratica alheia a improvisacao', 'E formato apenas para cantores'], undefined, 'Clase 7'),
    q('Que saxofonistas participaram da batalha de 1934 citada?', 'Coleman Hawkins, Lester Young, Ben Webster e Hershel Evans', ['Getz, Rollins, Shorter e Coltrane', 'Bechet, Parker, Dolphy e Mulligan', 'Carter, Konitz, Desmond e Gordon', 'Basie, Ellington, Goodman e Shaw'], undefined, 'Clase 7'),
    q('Que meio difundiu massivamente a jam de Billie Holiday em 1956?', 'NBC', ['BBC', 'Radio Habana', 'France Musique', 'Televisa'], undefined, 'Clase 7'),
    q('Que pratica de Kansas City antecipa a logica do pequeno grupo moderno?', 'A rotacao flexivel de solistas sobre uma base ritmica estavel', ['A proibicao do solo individual', 'O uso exclusivo de obras sacras', 'A orquestracao fechada sem espaco livre', 'A eliminacao do blues do repertorio'], undefined, 'Clase 7'),
  ],
  8: [
    q('Sobre o que Duke Ellington escrevia boa parte de sua harmonia?', 'Sobre o timbre de seus proprios solistas', ['Sobre padroes anonimos sem musicos concretos', 'Sobre formulas militares', 'Apenas sobre harmonia barroca', 'Sem pensar na orquestra real'], undefined, 'Clase 8'),
    q('Que peca de Billy Strayhorn foi pensada para Johnny Hodges?', 'Passion Flower', ['Take Five', 'Blue Monk', 'So What', 'A Night in Tunisia'], undefined, 'Clase 8'),
    q('O que caracteriza os head arrangements associados a Count Basie?', 'Baseiam-se em materiais nao escritos fixados pela pratica coletiva', ['Sao partituras sem improvisacao', 'Eliminam os riffs', 'Usam apenas instrumentos classicos', 'Exigem coro misto'], undefined, 'Clase 8'),
    q('O que e um head riff segundo a aula?', 'Uma frase curta, combinada e repetida', ['Uma introducao obrigatoria de 32 compassos', 'Um solo de bateria livre', 'Uma pausa antes do bridge', 'Uma melodia sem ritmo'], undefined, 'Clase 8'),
    q('Que funcao os riffs de secao podem ter?', 'Servir de base harmonica e resposta ao solista', ['Substituir toda a melodia definitivamente', 'Eliminar a secao ritmica', 'Impedir qualquer repeticao', 'Transformar o swing em marcha'], undefined, 'Clase 8'),
    q('Que procedimento compositivo e atribuido a Monk?', 'Transformar improvisacoes e acompanhamentos em temas', ['Copiar melodias de opera', 'Escrever apenas para cordas classicas', 'Evitar qualquer relacao entre solo e composicao', 'Eliminar a sincopa do jazz'], undefined, 'Clase 8'),
    q('De que standard deriva Evidence segundo os apontes?', 'Just You, Just Me', ['Body and Soul', 'Round Midnight', 'Cherokee', 'St. Louis Blues'], undefined, 'Clase 8'),
    q('Que traco define o enfoque de Ellington frente a uma escrita generica?', 'Escrever para personalidades sonoras concretas', ['Neutralidade timbrica absoluta', 'Rejeicao ao colorido individual', 'Homogeneidade vocal de coro', 'Eliminacao da secao de metais'], undefined, 'Clase 8'),
    q('O que representa One O Clock Jump no universo de Basie?', 'Um exemplo central do idioma de riffs e head arrangements', ['Uma balada europeia sem improvisacao', 'Um solo de piano classico', 'Uma suite coral religiosa', 'Uma peca modal dos anos 60'], undefined, 'Clase 8'),
    q('Que relacao entre composicao e arranjo esta no centro desta aula?', 'Eles podem nascer do som coletivo e das pessoas concretas do grupo', ['Dependem so da partitura escrita em estudio', 'Nao tem relacao com improvisacao', 'Limitam-se a copiar standards', 'O arranjo elimina a personalidade do musico'], undefined, 'Clase 8'),
    q('Que nome aparece ao lado de Ellington como colaborador compositivo essencial?', 'Billy Strayhorn', ['Fats Navarro', 'Billie Holiday', 'Charles Mingus', 'Clifford Brown'], undefined, 'Clase 8'),
    q('O que distingue um section riff de um head riff?', 'O de secao costuma ser atribuido a uma familia instrumental dentro do arranjo', ['O head riff e sempre da bateria', 'O section riff nao tem ritmo', 'O head riff nao se repete nunca', 'O section riff so existe na musica classica'], undefined, 'Clase 8'),
    q('Que visao final a aula deixa sobre o arranjo jazzistico?', 'Ele pode ser construcao colaborativa tanto quanto escrita autoral', ['E sempre simples copia literal de outro tema', 'Nao tem valor artistico frente ao solo', 'Nao depende do timbre', 'Se opoe a identidade da banda'], undefined, 'Clase 8'),
  ],
  9: [
    q('De que tradicao procedem as marching bands citadas nesta aula?', 'Das bandas militares', ['Dos quartetos de cordas vienenses', 'Da opera italiana', 'Dos coros galeses', 'Do gamelao javanes'], undefined, 'Clase 9'),
    q('Que instrumento levava a melodia em muitos conjuntos de New Orleans?', 'Trompete ou corneta', ['Contrabaixo', 'Vibrafone', 'Guitarra eletrica', 'Orgao'], undefined, 'Clase 9'),
    q('Que papel o clarinete cumpria nos conjuntos iniciais?', 'Contramelodia', ['Marcacao do baixo', 'Substituir a bateria', 'Fazer apenas acordes longos', 'Tocar so riffs de metais'], undefined, 'Clase 9'),
    q('Que funcao se atribui ao trombone na formacao de New Orleans?', 'Marcar as mudancas harmonicas', ['Levar sempre a melodia principal', 'Fazer walking bass', 'Substituir o piano nos bridges', 'Cantar o estribilho'], undefined, 'Clase 9'),
    q('O que a trompete simboliza segundo Wynton Marsalis?', 'Poder e autoridade espiritual', ['Fraqueza timbrica', 'Rejeicao do blues', 'Uniformidade coral', 'Silencio ritual'], undefined, 'Clase 9'),
    q('Que traco singular teve a formacao musical de Bix Beiderbecke?', 'Foi em grande parte autodidata', ['Formou-se exclusivamente em Paris', 'Estudou apenas orgao liturgico', 'Nunca tocou corneta', 'Aprendeu unicamente por escrita serial'], undefined, 'Clase 9'),
    q('Que cantor aparece como protegido de Bix e primeiro grande vocalista branco ligado ao jazz?', 'Bing Crosby', ['Frank Sinatra', 'Nat King Cole', 'Tony Bennett', 'Mel Torme'], undefined, 'Clase 9'),
    q('Que mudanca as big bands introduzem em relacao a instrumentacao inicial?', 'Uma organizacao por secoes de metais e saxes', ['O desaparecimento total dos sopros', 'A reducao a duos sem bateria', 'O uso exclusivo de cordas classicas', 'A eliminacao do clarinete de toda a historia'], undefined, 'Clase 9'),
    q('Que traco tem orquestras modernas como as de Thornhill ou Gil Evans?', 'Incorporam instrumentos menos habituais como fagote ou clarinete baixo', ['Rejeitam por completo qualquer sopro', 'Funcionam sem arranjos', 'Nao usam secao ritmica', 'Limitam-se ao formato militar original'], undefined, 'Clase 9'),
    q('Que banda se associa a presenca poderosa de metais e grande variedade instrumental nesta aula?', 'A de Charles Mingus', ['A de Claudio Monteverdi', 'A de Antonio Vivaldi', 'A de Johann Strauss', 'A de Philip Glass'], undefined, 'Clase 9'),
    q('Que relacao se estabelece entre marching bands e os primeiros grupos de jazz?', 'As primeiras formacoes de jazz nascem transformando essa base instrumental', ['Nao ha qualquer relacao historica', 'As marching bands surgiram apos o bebop', 'O jazz eliminou todos os metais', 'As marching bands eram grupos vocais'], undefined, 'Clase 9'),
    q('Que instrumento aparece ao lado de trompetes, trombones e clarinetes nas marching bands?', 'Tuba', ['Sitar', 'Oboe d amore', 'Cravo', 'Mandolina'], undefined, 'Clase 9'),
    q('Que ideia central a aula deixa sobre a orquestra de jazz?', 'A instrumentacao evolui, mas preserva dialogo entre secoes, cor e funcao', ['Todas as orquestras de jazz sao identicas', 'A orquestra elimina o solista', 'A evolucao reduz o colorido instrumental', 'O formato moderno impede arranjos'], undefined, 'Clase 9'),
  ],
  10: [
    q('Que instrumento Armstrong liderava nos Hot Five e Hot Seven?', 'Trompete', ['Piano', 'Vibrafone', 'Contrabaixo', 'Sax baritono'], undefined, 'Clase 10'),
    q('Com que conjunto Jelly Roll Morton gravou uma sessao interracial precoce?', 'New Orleans Rhythm Kings', ['Modern Jazz Quartet', 'Jazz Messengers', 'Big band de Kenton', 'Quinteto de Davis dos anos 60'], undefined, 'Clase 10'),
    q('O que caracteriza o stomp de Morton segundo os apontes?', 'Ritmo para marcar com o pe, sincopa enganosa e estrutura pluritematica', ['Ausencia total de ritmo marcado', 'Rejeicao do piano', 'Forma de blues modal de um unico acorde', 'Uso exclusivo de ternario lento'], undefined, 'Clase 10'),
    q('Que obra de 1926 e citada como equilibrio ideal entre composicao e improvisacao?', 'Black Bottom Stomp', ['Take the A Train', 'Naima', 'Spain', 'So What'], undefined, 'Clase 10'),
    q('Quem e apresentado como primeiro grande guitarrista solista improvisador?', 'Eddie Lang', ['Wes Montgomery', 'Pat Metheny', 'Jim Hall', 'Grant Green'], undefined, 'Clase 10'),
    q('Com que violinista Eddie Lang colaborou regularmente?', 'Joe Venuti', ['Stephane Grappelli', 'Jean-Luc Ponty', 'Didier Lockwood', 'Stuff Smith'], undefined, 'Clase 10'),
    q('Que fato historico a formacao do trio de Benny Goodman em 1935 sublinha?', 'Foi um dos primeiros pequenos grupos interraciais de grande impacto', ['Eliminou a improvisacao do swing', 'Foi o primeiro trio sem secao ritmica', 'Criou-se para tocar apenas musica religiosa', 'Deslocou por completo o sax do jazz'], undefined, 'Clase 10'),
    q('Que vibrafonista foi adicionado depois ao entorno de Goodman?', 'Lionel Hampton', ['Milt Jackson', 'Bobby Hutcherson', 'Gary Burton', 'Cal Tjader'], undefined, 'Clase 10'),
    q('Que acidente marcou a tecnica de Django Reinhardt?', 'Uma queimadura que lhe deixou dois dedos realmente funcionais na mao esquerda', ['A perda do ouvido direito', 'Uma fratura que o impediu de usar palheta', 'Um problema respiratorio com a trompete', 'Lesao que o obrigou a abandonar a guitarra'], undefined, 'Clase 10'),
    q('Que grupo Django fundou com Stephane Grappelli?', 'Quintette du Hot Club de France', ['The Jazz Crusaders', 'Weather Report', 'Thelonious Monk Quartet', 'Jazz at the Philharmonic'], undefined, 'Clase 10'),
    q('Qual era a instrumentacao tipica do combo bebop indicada na aula?', 'Trompete, sax, piano, contrabaixo e bateria', ['Dois violinos, viola e cello', 'Piano, harpa e oboe', 'Tres trombones e coro', 'Apenas guitarra e percussao'], undefined, 'Clase 10'),
    q('Que peca de Charlie Parker aparece como exemplo de bebop maduro?', 'Confirmation', ['C Jam Blues', 'Mood Indigo', 'Autumn Leaves', 'Round Midnight'], undefined, 'Clase 10'),
    q('Que figura aparece como ponte entre bop e free jazz no pequeno grupo?', 'Eric Dolphy', ['Benny Goodman', 'Fats Waller', 'Bix Beiderbecke', 'Bubber Miley'], undefined, 'Clase 10'),
  ],
  11: [
    q('Como a missao da secao ritmica se divide na aula 11?', 'Apoio harmonico, linha de baixo e percussao', ['Melodia, coro e cenografia', 'Apenas metais, vozes e silencio', 'Harpa, flauta e violino', 'Compasso, bridge e coda'], undefined, 'Clase 11'),
    q('Que tecnica Walter Page criou para sustentar a harmonia?', 'Walking bass', ['Scat singing', 'Growl', 'Stop-time', 'Head arrangement'], undefined, 'Clase 11'),
    q('Quantas semibreves?','Quatro negras por compasso no walking bass', ['Uma negra', 'Duas negras', 'Tres negras', 'Seis negras'], 'A ideia do walking bass e sustentar quatro pulsos por compasso.', 'Clase 11'),
    q('O que significa comping no contexto da secao ritmica?', 'Acompanhar com acordes complementando o solista', ['Improvisar sem ouvir ninguem', 'Marcar so o tempo forte do bumbo', 'Cantar o tema principal', 'Tocar exclusivamente em rubato'], undefined, 'Clase 11'),
    q('Que guitarrista integra a historica secao ritmica de Count Basie?', 'Freddie Green', ['Charlie Christian', 'Eddie Lang', 'Django Reinhardt', 'Jim Hall'], undefined, 'Clase 11'),
    q('Que traco define o toque de Freddie Green?', 'Consistencia implacavel no sustento do swing', ['Uso de distorcao eletrica', 'Eliminacao do pulso', 'Preferencia por solos longos de rock', 'Substituicao da harmonia por ruido'], undefined, 'Clase 11'),
    q('Que baterista aparece ao lado de Walter Page e Freddie Green na secao de Basie?', 'Jo Jones', ['Buddy Rich', 'Max Roach', 'Kenny Clarke', 'Elvin Jones'], undefined, 'Clase 11'),
    q('Que tecnica do contrabaixo e apontada como fundamental no jazz?', 'Pizzicato', ['Tremolo romantico constante', 'Uso exclusivo do arco', 'Glissando operistico permanente', 'Afinacao barroca scordatura'], undefined, 'Clase 11'),
    q('O que o piano pode fazer para contradizer criativamente o pulso base?', 'Colocar acordes entre os tempos', ['Eliminar toda harmonia do grupo', 'Duplicar sempre a melodia exata', 'Tocar so pedais longos', 'Silenciar a bateria'], undefined, 'Clase 11'),
    q('Qual e o papel do ride cymbal no swing moderno?', 'Reforcar o pulso continuo da base ritmica', ['Substituir toda a harmonia', 'Usar-se so em baladas sem beat', 'Eliminar a funcao do contrabaixo', 'Marcar exclusivamente o primeiro compasso'], undefined, 'Clase 11'),
    q('Que metrica basica a aula menciona como habitual no jazz?', 'Beat de 2 ou 4 tempos', ['7 e 9 tempos como norma', 'Apenas 5 por 4 em todo repertorio', 'Unicamente compasso livre', 'Sempre 3 por 8'], undefined, 'Clase 11'),
    q('Que ideia resume a relacao entre bateria, baixo e piano na secao ritmica?', 'Compartilham base estavel, mas podem tensiona-la com sincopa e resposta ao solista', ['Cada um toca sem relacao com os demais', 'Todos duplicam a melodia principal', 'O baixo dirige tudo sem ouvir o piano', 'A bateria evita qualquer dialogo'], undefined, 'Clase 11'),
    q('Que instrumento pode cumprir funcao harmonica alem do piano segundo a aula?', 'Vibrafone', ['Caixa clara', 'Trompete com sordina', 'Bumbo', 'Clarinete baixo como norma'], undefined, 'Clase 11'),
  ],
  12: [
    q('Que ideia a aula 12 repete sobre improvisacao?', 'Ela precisa de um material ou estrutura de partida', ['Surge sem qualquer base musical', 'Se opoe a todo tema previo', 'So existe no free jazz', 'Limita-se ao canto religioso'], undefined, 'Clase 12'),
    q('Que tres estrategias de improvisacao Barry Kernfeld identifica?', 'Parafrase, formula e abordagens modais', ['Riff, shout e fuga', 'Canon, coral e rondo', 'Scat, growl e crooning', 'Marcha, valsa e polca'], undefined, 'Clase 12'),
    q('O que faz a parafrase na improvisacao?', 'Embeleza e transforma a melodia original', ['Elimina toda referencia melodica desde o inicio', 'Substitui o ritmo por silencio', 'Usa so acordes sem linha melodica', 'Rejeita o fraseado pessoal'], undefined, 'Clase 12'),
    q('O que caracteriza a estrategia formulaica?', 'Apoia-se fortemente nas mudancas harmonicas e seus padroes', ['Nega a harmonia', 'Usa apenas uma nota por chorus', 'Repete a melodia sem varia-la', 'So funciona na musica classica'], undefined, 'Clase 12'),
    q('Que saxofonista representa um enfoque harmonico que se afasta da melodia para criar variacoes inventadas?', 'Coleman Hawkins', ['Sidney Bechet', 'Paul Desmond', 'Stan Getz', 'Johnny Hodges'], undefined, 'Clase 12'),
    q('Que tema de Miles Davis e usado para explicar a improvisacao modal?', 'So What', ['Blue Monk', 'Black Bottom Stomp', 'Take the A Train', 'One O Clock Jump'], undefined, 'Clase 12'),
    q('Que modos alternam em So What segundo a aula?', 'Dorico de re e dorico de mi bemol', ['Jonico de do e lidio de fa', 'Frigio de mi e locrio de si', 'Mixolidio de sol e eolio de la', 'Apenas cromatismo sem modo'], undefined, 'Clase 12'),
    q('Que vantagem a improvisacao modal da ao solista?', 'Mais liberdade melodica sobre base harmonica simplificada', ['Obrigacao de seguir mais acordes por compasso', 'Eliminacao de toda escuta grupal', 'Impossibilidade de repetir motivos', 'Desaparecimento do swing'], undefined, 'Clase 12'),
    q('Que album de 1961 aparece como referencia para o free jazz?', 'Free Jazz de Ornette Coleman', ['Kind of Blue de Miles Davis', 'Birth of the Cool', 'Time Out', 'Mingus Ah Um'], undefined, 'Clase 12'),
    q('Que traco o free jazz conserva apesar de romper com acordes tradicionais?', 'A voz e o sound individual de cada musico', ['A forma estrita AABA em todas as pecas', 'O walking bass obrigatorio', 'O canto crooner como centro', 'A harmonia tonal de Broadway'], undefined, 'Clase 12'),
    q('Como o ritmo e entendido no free jazz segundo a aula?', 'Como impulso energetico global mais que funcao fixa por secoes', ['Como two beat militar constante', 'Como funcao exclusiva do piano', 'Como silencio entre improvisacoes', 'Como repeticao de polca'], undefined, 'Clase 12'),
    q('Que musicos sao citados junto a Ornette Coleman no entorno do free jazz?', 'Cecil Taylor e o ultimo Coltrane', ['Bing Crosby e Peggy Lee', 'Bix e Venuti', 'Goodman e Hampton', 'Joplin e Turpin'], undefined, 'Clase 12'),
    q('Que oposicao historica o texto menciona entre Europa e improvisacao?', 'A musica classica europeia a marginalizou por cerca de 200 anos', ['A Europa a manteve como unica pratica possivel', 'Nunca existiu improvisacao antes do jazz', 'A improvisacao nasceu so no rock', 'Apenas Franz Liszt a rejeitou'], undefined, 'Clase 12'),
  ],
  13: [
    q('Como a cultura do jazz moderno se define frente ao entertainment?', 'Como cultura separada que se autodefine diante dele', ['Como simples variante do espetaculo comercial', 'Como musica sem identidade propria', 'Como genero exclusivamente teatral', 'Como subgenero da opereta'], undefined, 'Clase 13'),
    q('Que tipo de espacos os musicos de jazz frequentavam nos anos 20?', 'Clubes noturnos, circuitos de minstrel, circo e rua', ['Apenas auditorios academicos', 'Exclusivamente igrejas', 'Somente universidades', 'So festivais de musica classica'], undefined, 'Clase 13'),
    q('Como Louis Armstrong se apresentava a si proprio nesse periodo?', 'Como entertainer obrigado a agradar o publico', ['Como compositor de camara', 'Como critico musical', 'Como regente sinfonico', 'Como musicologo'], undefined, 'Clase 13'),
    q('Quem organizou deliberadamente em estudio os Hot Five e Hot Seven?', 'Richard M. Jones', ['Count Basie', 'John Hammond', 'Gunther Schuller', 'Miles Davis'], undefined, 'Clase 13'),
    q('Que peca e citada como exemplo de Armstrong ainda influenciado pelo vaudeville?', 'Big Butter and Egg Man', ['So What', 'Take Five', 'Song for My Father', 'Goodbye Pork Pie Hat'], undefined, 'Clase 13'),
    q('Que mudanca Potato Head Blues representa?', 'Passo rumo a improvisacao mais harmonica com acordes quebrados', ['Abandono total do blues', 'Retorno ao ragtime rigido', 'Aparicao do free jazz', 'Eliminacao do solo de trompete'], undefined, 'Clase 13'),
    q('Que clube aparece como grande cenario do refinamento orquestral de Ellington?', 'Cotton Club', ['Blue Note', 'Village Vanguard', 'Birdland', 'Ronnie Scott s'], undefined, 'Clase 13'),
    q('Que eixo geografico aparece como passagem para a independencia do jazz em Nova York?', 'A rua 52 e o Minton s', ['Broadway e Harlem classico exclusivamente vocal', 'Central Park e Carnegie Hall', 'Brooklyn e Queens sem clubes', 'O distrito financeiro'], undefined, 'Clase 13'),
    q('Que pianista e citado ligado ao Onyx dentro do ambiente da rua 52?', 'Art Tatum', ['Bill Evans', 'Bud Powell', 'Herbie Hancock', 'McCoy Tyner'], undefined, 'Clase 13'),
    q('Quem integrava o nucleo basico dos Hot Five segundo a aula?', 'Kid Ory, Johnny Dodds, Johnny St. Cyr, Lil Hardin e Armstrong', ['Dizzy, Parker, Powell, Roach e Mingus', 'Ellington, Hodges, Carney, Strayhorn e Basie', 'Getz, Mulligan, Brubeck, Desmond e Hall', 'Miles, Coltrane, Evans, Chambers e Cobb'], undefined, 'Clase 13'),
    q('O que a evolucao entre Big Butter and Egg Man e Potato Head Blues mostra?', 'A passagem de uma logica de espetaculo para afirmacao mais jazzistica', ['O desaparecimento de Armstrong do jazz', 'A renuncia a improvisar', 'A substituicao da trompete por clarinete', 'O retorno a musica coral'], undefined, 'Clase 13'),
    q('Que ideia central a aula deixa sobre entertainment e jazz?', 'Conviveram por um tempo, mas o jazz foi delimitando autonomia propria', ['Sempre foram identicos e sem conflito', 'O entertainment nasceu depois do bop', 'O jazz rejeitou o publico desde o inicio', 'A cultura do jazz nao teve relacao com clubes'], undefined, 'Clase 13'),
    q('Que recurso tecnico aparece associado ao solo de Armstrong nesta etapa?', 'Stop-time chorus', ['Canon gregoriano', 'Fuga serial', 'Modulacao dodecafonica', 'Pedal barroco'], undefined, 'Clase 13'),
  ],
  14: [
    q('Que diferenca de fundo separa o canto jazz do canto popular comercial segundo a aula?', 'A exigencia de improvisar e reinterpretar pessoalmente', ['A obrigacao de cantar sem ritmo', 'A proibicao do swing', 'A ausencia de letra', 'O uso exclusivo do ingles'], undefined, 'Clase 14'),
    q('O que Carol Sloane afirma sobre o cantor de jazz?', 'Que e alguem que se arrisca', ['Que nunca improvisa', 'Que deve copiar sempre a gravacao original', 'Que so canta baladas lentas', 'Que depende do coro'], undefined, 'Clase 14'),
    q('Que aspecto Sue Kibbey destaca no canto jazzistico?', 'Sincopa, timing e swing', ['Rigidez operistica', 'Neutralidade timbrica', 'Ausencia de fraseado', 'Leitura exata sem variacao'], undefined, 'Clase 14'),
    q('Que cantora representa o vaudeville blues nesta primeira parte?', 'Ma Rainey', ['Billie Holiday', 'June Christy', 'Peggy Lee', 'Dinah Washington'], undefined, 'Clase 14'),
    q('Que tecnica vocal permitia a Ma Rainey impor-se antes do microfone?', 'Shout', ['Falsete lirico europeu', 'Sussurro cool', 'Voz branca coral', 'Sprechgesang'], undefined, 'Clase 14'),
    q('Que dado se destaca da carreira de Bessie Smith?', 'Gravou cerca de 160 discos', ['Gravou so 12 musicas', 'Nunca gravou blues', 'Foi apenas atriz de teatro', 'Cantou so com big bands brancas'], undefined, 'Clase 14'),
    q('O que Armstrong aportou a voz de jazz com o scat?', 'O uso de silabas como material melodico e ritmico instrumental', ['A eliminacao do ritmo no canto', 'A obrigacao de cantar letras completas', 'O retorno ao recitativo sem swing', 'A voz sem improvisacao'], undefined, 'Clase 14'),
    q('Que crooner branco sobreviveu de forma autentica ao periodo jazz-crooning segundo a aula?', 'Bing Crosby', ['Dean Martin', 'Michael Buble', 'Elvis Presley', 'Tom Jones'], undefined, 'Clase 14'),
    q('O que Ellington buscava em varias de suas cantoras?', 'Flexibilidade, negritude sonora e amplitude de registro', ['Emissao operistica homogenea', 'Ausencia total de vibrato e swing', 'Neutralidade timbrica absoluta', 'Apenas canto infantil'], undefined, 'Clase 14'),
    q('Que ideia central a aula deixa sobre tradicao europeia e canto jazz?', 'O jazz exige superar o costume de reproduzir sem transformar', ['O jazz copia sem mudancas o modelo europeu', 'A tradicao europeia elimina o fraseado', 'Nao ha diferenca entre os enfoques', 'Improvisacao so vale para instrumentos'], undefined, 'Clase 14'),
    q('Como Kitty Margolis entende o canto jazzistico?', 'Como pratica com improvisacao, complexidade ritmica, interpretacao de letra e soulfulness', ['Como mera afinacao academica', 'Como estilo sem swing', 'Como leitura coral exata', 'Como canto apenas de notas longas'], undefined, 'Clase 14'),
    q('Que relacao a aula estabelece entre voz e instrumento no jazz?', 'A voz pode comportar-se como instrumento e absorver recursos improvisatorios', ['A voz deve evitar qualquer gesto instrumental', 'Apenas a trompete pode improvisar', 'O canto jazz nao tem relacao com timbre', 'A voz fica fora da cultura do jazz'], undefined, 'Clase 14'),
    q('Que nome feminino abre a linhagem do blues teatral e vocal desta etapa?', 'Ma Rainey', ['Sarah Vaughan', 'Ella Fitzgerald', 'Anita O Day', 'Carmen McRae'], undefined, 'Clase 14'),
  ],
  15: [
    q('Que grande orquestra teve Peggy Lee como cantora em 1943?', 'A de Benny Goodman', ['A de Duke Ellington', 'A de Count Basie', 'A de Charles Mingus', 'A de Gil Evans'], undefined, 'Clase 15'),
    q('Que cantora branca modelou a primeira etapa de Ella Fitzgerald?', 'Connie Boswell', ['Peggy Lee', 'June Christy', 'Anita O Day', 'Billie Holiday'], undefined, 'Clase 15'),
    q('Com que musico Ella desenvolveu proximidade que reforcou seu scat ligado ao bop?', 'Ray Brown', ['Lester Young', 'Bix Beiderbecke', 'Cootie Williams', 'Freddie Green'], undefined, 'Clase 15'),
    q('Quem descobriu Billie Holiday no Harlem em 1932?', 'John Hammond', ['Norman Granz', 'George Avakian', 'Leonard Feather', 'Richard M. Jones'], undefined, 'Clase 15'),
    q('Que qualidade do canto de Billie Holiday a aula destaca?', 'Ela reforma melodia e ritmo de forma profundamente pessoal', ['Ela copia literalmente a melodia escrita', 'Evita qualquer vinculo com a letra', 'Canta com voz operistica expansiva', 'Improvisa apenas scat sem texto'], undefined, 'Clase 15'),
    q('A que instrumento Schuller compara o timbre de Billie Holiday?', 'Corne ingles', ['Trombone baixo', 'Fagote barroco', 'Ride cymbal', 'Banjo tenor'], undefined, 'Clase 15'),
    q('Que cancao de 1939 mudou o rumo interpretativo de Billie Holiday para um dramatismo maior?', 'Strange Fruit', ['How High the Moon', 'A-Tisket, A-Tasket', 'Lullaby of Birdland', 'Mr. Paganini'], undefined, 'Clase 15'),
    q('Que cantora substituiu Anita O Day na orquestra de Stan Kenton?', 'June Christy', ['Ella Fitzgerald', 'Peggy Lee', 'Sarah Vaughan', 'Dinah Shore'], undefined, 'Clase 15'),
    q('Que traco se associa a vocalidade cool de June Christy?', 'Quase ausencia de vibrato e timbre algo aspera', ['Shout potente de blues classico', 'Scat agressivo de bebop extremo', 'Colorido nasal com growl continuo', 'Cor exclusivamente lirico-operistica'], undefined, 'Clase 15'),
    q('Que tesitura perfeita se atribui a Sarah Vaughan?', 'Contralto', ['Tenor', 'Baritono', 'Soprano ligeira sem graves', 'Baixo profundo'], undefined, 'Clase 15'),
    q('Que formacao inicial ajudou Sarah Vaughan a entender harmonia e piano?', 'O coro batista', ['A banda militar de New Orleans', 'A orquestra de camera vienense', 'O coro gregoriano romano', 'A escola de bel canto napolitano'], undefined, 'Clase 15'),
    q('O que Sarah Vaughan aprendeu para cantar bop com autoridade?', 'Decomposicao harmonica, saltos de oitava e invencao timbrica', ['Evitar toda harmonia complexa', 'Cantar apenas num registro central', 'Eliminar a improvisacao', 'Usar apenas repertorio de vaudeville'], undefined, 'Clase 15'),
    q('Que ideia resume melhor a segunda parte do canto jazz?', 'A maturidade vocal chega quando cada cantora torna irrepetivel sua relacao com ritmo, timbre e melodia', ['A excelencia consiste em soar identico a outros cantores', 'O jazz vocal se separa da improvisacao', 'A voz perde importancia diante da orquestra', 'Somente o repertorio comercial define qualidade'], undefined, 'Clase 15'),
  ],
};

export const introLessonQuizSeed = LESSON_QUIZ_BANKS[1];

export function buildLessonQuizSeedData(questions: QuizSeedQuestion[]) {
  return questions.map((question) => ({
    prompt: question.prompt,
    explanation: question.explanation,
    sourceLabel: question.sourceLabel,
    options: {
      create: question.options.map((option, index) => ({
        label: OPTION_LABELS[index],
        text: option.text,
        isCorrect: option.isCorrect,
        position: index,
      })),
    },
  }));
}